// <auto-generated />
using System;
using Lexias.Services.PaymentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexias.Services.PaymentAPI.Migrations
{
    [DbContext(typeof(AppDbContextPayment))]
    [Migration("20241119134547_SeedIncluded")]
    partial class SeedIncluded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lexias.Services.PaymentAPI.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(24, 4)
                        .HasColumnType("decimal(24,4)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = "payment1",
                            Amount = 50.00m,
                            OrderId = "order1111",
                            PaymentDate = new DateTime(2024, 11, 9, 13, 45, 47, 439, DateTimeKind.Utc).AddTicks(7235),
                            Status = 1
                        },
                        new
                        {
                            PaymentId = "payment2",
                            Amount = 100.00m,
                            OrderId = "order2222",
                            PaymentDate = new DateTime(2024, 11, 14, 13, 45, 47, 439, DateTimeKind.Utc).AddTicks(8051),
                            Status = 0
                        },
                        new
                        {
                            PaymentId = "payment3",
                            Amount = 75.00m,
                            OrderId = "order3333",
                            PaymentDate = new DateTime(2024, 11, 17, 13, 45, 47, 439, DateTimeKind.Utc).AddTicks(8057),
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
