// <auto-generated />
using Lexias.Services.WarehouseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexias.Services.WarehouseAPI.Migrations
{
    [DbContext(typeof(AppDbContextWarehouse))]
    [Migration("20241119142454_SeedIncluded")]
    partial class SeedIncluded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lexias.Services.WarehouseAPI.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "product1",
                            Category = "Men",
                            Color = "Red",
                            Description = "Comfortable cotton T-shirt",
                            ItemType = 1,
                            Name = "T-Shirt",
                            Price = 20.00m,
                            StockQuantity = 500
                        },
                        new
                        {
                            ProductId = "product2",
                            Category = "Men",
                            Color = "Blue",
                            Description = "Slim fit blue jeans",
                            ItemType = 2,
                            Name = "Jeans",
                            Price = 40.00m,
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = "product3",
                            Category = "Women",
                            Color = "Black",
                            Description = "Warm winter jacket",
                            ItemType = 4,
                            Name = "Jacket",
                            Price = 60.00m,
                            StockQuantity = 600
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
