// <auto-generated />
using System;
using Lexias.Services.OrderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexias.Services.OrderAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241119131448_SeedThem")]
    partial class SeedThem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lexias.Services.OrderAPI.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "order1111",
                            CustomerId = "customer1",
                            OrderDate = new DateTime(2024, 11, 16, 13, 14, 48, 280, DateTimeKind.Utc).AddTicks(2066),
                            OrderStatus = 5,
                            TotalAmount = 80.00m
                        },
                        new
                        {
                            OrderId = "order2222",
                            CustomerId = "customer2",
                            OrderDate = new DateTime(2024, 11, 18, 13, 14, 48, 280, DateTimeKind.Utc).AddTicks(3154),
                            OrderStatus = 0,
                            TotalAmount = 60.00m
                        },
                        new
                        {
                            OrderId = "order3333",
                            CustomerId = "customer3",
                            OrderDate = new DateTime(2024, 11, 17, 13, 14, 48, 280, DateTimeKind.Utc).AddTicks(3161),
                            OrderStatus = 6,
                            TotalAmount = 80.00m
                        });
                });

            modelBuilder.Entity("Lexias.Services.OrderAPI.Models.OrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = "orderitem1",
                            OrderId = "order1111",
                            Price = 20.00m,
                            ProductId = "product1",
                            ProductName = "T-Shirt",
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = "orderitem2",
                            OrderId = "order1111",
                            Price = 40.00m,
                            ProductId = "product2",
                            ProductName = "Jeans",
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = "orderitem3",
                            OrderId = "order2222",
                            Price = 60.00m,
                            ProductId = "product3",
                            ProductName = "Jacket",
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = "orderitem4",
                            OrderId = "order3333",
                            Price = 50.00m,
                            ProductId = "product4",
                            ProductName = "Sneakers",
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = "orderitem5",
                            OrderId = "order3333",
                            Price = 10.00m,
                            ProductId = "product5",
                            ProductName = "Hat",
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Lexias.Services.OrderAPI.Models.OrderItem", b =>
                {
                    b.HasOne("Lexias.Services.OrderAPI.Models.Order", "Order")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Lexias.Services.OrderAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItemsList");
                });
#pragma warning restore 612, 618
        }
    }
}
